#!/usr/bin/env bash
export LC_ALL=C
set -e -o pipefail

# Check if macOS SDK is present, if not, download it
if [ ! -d "/dash/depends/SDKs/Xcode-12.1-12A7403-extracted-SDK-with-libcxx-headers" ]
then
    curl -L https://bitcoincore.org/depends-sources/sdks/Xcode-12.1-12A7403-extracted-SDK-with-libcxx-headers.tar.gz | tar -xz -C /dash/depends/SDKs
fi

cd /dash
git status >> /dev/null
git config --global --add safe.directory /dash

./contrib/guix/guix-build
