#!/usr/bin/env bash
export LC_ALL=C
set -e -o pipefail

cd /dash
COMMIT_ID=guix-build-$(git rev-parse --short=12 HEAD)

printf "Binaries:\n"
( \
SRC_PATH_PREFIX=guix-build-${COMMIT_ID}/distsrc- && \
sha256sum ${SRC_PATH_PREFIX}*/src/dash{d,-cli,-tx,-wallet}{,.exe} && \
sha256sum ${SRC_PATH_PREFIX}*/src/qt/dash-qt{,.exe} && \
sha256sum ${SRC_PATH_PREFIX}*/src/test/test_dash{,.exe} \
) | sort -k 2

printf "Archives:\n"
find guix-build-"${COMMIT_ID}"/output -type f | grep -v SHA256 | xargs sha256sum | sort -k 2
