[workspace]
resolver = "2"
exclude = [
  "rust/grovedb/grovedb/grovedbg",
  "rust/grovedb/node-grove",
]
members = [
  "rust/chirp",
  "rust/grovedb/costs",
  "rust/grovedb/grovedb",
  "rust/grovedb/grovedb-element",
  "rust/grovedb/grovedb-epoch-based-storage-flags",
  "rust/grovedb/grovedb-version",
  "rust/grovedb/grovedbg-types",
  "rust/grovedb/merk",
  "rust/grovedb/path",
  "rust/grovedb/storage",
  "rust/grovedb/visualize",
  "rust/grovedb_cxx",
]

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[profile.dev]
codegen-units = 1
panic = "abort"
