option('build_tests',
  type: 'boolean',
  value: true,
  description: 'Build unit tests'
)

option('grovedb_cxx_build_dir',
  type: 'string',
  value: '',
  description: 'Path to grovedb_cxx build directory (auto-detected if empty, ignored if use_rustdeps=true)'
)

option('harden_build',
  type: 'boolean',
  value: true,
  description: 'Set hardening compiler, linker and preprocessor flags'
)

option('rustdeps_build_dir',
  type: 'string',
  value: '',
  description: 'Path to rustdeps build directory (auto-detected if empty)'
)

option('shared_library',
  type: 'boolean',
  value: true,
  description: 'Build shared library with pkg-config definitions (implicit with build_tests)'
)

option('suppress_external_warnings',
  type: 'boolean',
  value: true,
  description: 'Suppress warnings from external headers'
)

option('use_rustdeps',
  type: 'boolean',
  value: false,
  description: 'Link against librustdeps instead of libgrovedb_cxx'
)
