# syntax = edrevo/dockerfile-plus

FROM alpine:3.17

INCLUDE+ Dockerfile.base

RUN git clone https://github.com/dashpay/dash.git /dash

RUN mkdir base_cache sources SDKs

WORKDIR /dash

RUN mkdir -p depends/SDKs && \
    curl -L https://bitcoincore.org/depends-sources/sdks/Xcode-12.1-12A7403-extracted-SDK-with-libcxx-headers.tar.gz | tar -xz -C depends/SDKs

ENTRYPOINT ["/root/.config/guix/current/bin/guix-daemon","--build-users-group=guixbuild"]
