// Copyright (c) 2025 The Dash Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#include <evo/netinfo.h>

#include <coinjoin/client.h>
#include <chainparams.h>
#include <evo/deterministicmns.h>
#include <evo/simplifiedmns.h>
#include <netbase.h>
#include <util/check.h>
#include <util/system.h>

#include <univalue.h>

namespace {
static std::unique_ptr<const CChainParams> g_main_params{nullptr};

const bool IsNodeOnMainnet() { return Params().NetworkIDString() == CBaseChainParams::MAIN; }
const CChainParams& MainParams()
{
    // TODO: use real args here
    if (!g_main_params) g_main_params = CreateChainParams(ArgsManager{}, CBaseChainParams::MAIN);
    return *g_main_params;
}
} // anonymous namespace

UniValue ArrFromService(const CService& addr)
{
    UniValue obj(UniValue::VARR);
    obj.push_back(addr.ToStringAddrPort());
    return obj;
}

bool IsServiceDeprecatedRPCEnabled()
{
    const auto args = gArgs.GetArgs("-deprecatedrpc");
    return std::find(args.begin(), args.end(), "service") != args.end();
}

// Compatibility code to populate an array generated by MnNetInfo::GetJson() with Platform
// network information even though we don't store that in MnNetInfo.
UniValue MaybeAddPlatformNetInfo(const CDeterministicMN& dmn, const UniValue& arr)
{
    assert(arr.type() == UniValue::VOBJ);
    if (dmn.nType != MnType::Evo) return arr;
    CNetAddr addr{Assert(dmn.pdmnState)->netInfo->GetPrimary()}; UniValue ret{arr};
    ret.pushKV(PurposeToString(Purpose::PLATFORM_HTTP, /*lower=*/true), ArrFromService(CService(addr, dmn.pdmnState->platformHTTPPort)));
    ret.pushKV(PurposeToString(Purpose::PLATFORM_P2P, /*lower=*/true), ArrFromService(CService(addr, dmn.pdmnState->platformP2PPort)));
    return ret;
}

// Needed for classes that implement their own ToJson()
namespace {
template <typename T1>
UniValue IMaybeAddPlatformNetInfo(const T1& obj, const MnType& type, const UniValue& arr)
{
    assert(arr.type() == UniValue::VOBJ);
    if (type != MnType::Evo) return arr;
    CNetAddr addr{obj.netInfo->GetPrimary()}; UniValue ret{arr};
    ret.pushKV(PurposeToString(Purpose::PLATFORM_HTTP, /*lower=*/true), ArrFromService(CService(addr, obj.platformHTTPPort)));
    if constexpr (!std::is_same<T1, CSimplifiedMNListEntry>::value) /* CSimplifiedMNListEntry doesn't have this field */ {
        ret.pushKV(PurposeToString(Purpose::PLATFORM_P2P, /*lower=*/true), ArrFromService(CService(addr, obj.platformP2PPort)));
    }
    return ret;
}
} // anonymous namespace
UniValue MaybeAddPlatformNetInfo(const CDeterministicMNState& obj, const MnType& type, const UniValue& arr) {
    return IMaybeAddPlatformNetInfo(obj, type, arr);
}
UniValue MaybeAddPlatformNetInfo(const CProRegTx& obj, const UniValue& arr) {
    return IMaybeAddPlatformNetInfo(obj, obj.nType, arr);
}
UniValue MaybeAddPlatformNetInfo(const CProUpServTx& obj, const UniValue& arr) {
    return IMaybeAddPlatformNetInfo(obj, obj.nType, arr);
}
UniValue MaybeAddPlatformNetInfo(const CSimplifiedMNListEntry& obj, const MnType& type, const UniValue& arr) {
    return IMaybeAddPlatformNetInfo(obj, type, arr);
}

std::optional<std::reference_wrapper<const CService>> NetInfoEntry::GetAddrPort() const
{
    if (IsTypeBIP155(type)) {
        return data;
    }
    return std::nullopt;
}

// NetInfoEntry is a dumb object that doesn't enforce validation rules, that is the responsibility of
// types that utilize NetInfoEntry (MnNetInfo and others). IsTriviallyValid() is there to check if a
// NetInfoEntry object is properly constructed.
bool NetInfoEntry::IsTriviallyValid() const
{
    // Empty underlying data isn't a valid entry
    if (data == CService() || type == INVALID_TYPE) return false;
    // Type code should be truthful as it decides what underlying type is used when (de)serializing
    if (type != GetBIP155FromService(data)) return false;
    // Underlying data should at least meet surface-level validity checks
    if (!data.IsValid()) return false;
    // Type code should be supported by NetInfoEntry
    return IsTypeBIP155(type);
}

std::string NetInfoEntry::ToString() const
{
    return strprintf("CService(addr=%s, port=%d)", data.ToStringAddr(), data.GetPort());
}

std::string NetInfoEntry::ToStringAddrPort() const
{
    return data.ToStringAddrPort();
}

NetInfoStatus MnNetInfo::ValidateService(const CService& service)
{
    if (!service.IsValid()) {
        return NetInfoStatus::BadInput;
    }
    if (!service.IsIPv4()) {
        return NetInfoStatus::BadInput;
    }
    if (Params().RequireRoutableExternalIP() && !service.IsRoutable()) {
        return NetInfoStatus::BadInput;
    }

    const auto default_port_main = MainParams().GetDefaultPort();
    if (IsNodeOnMainnet() && service.GetPort() != default_port_main) {
        // Must use mainnet port on mainnet
        return NetInfoStatus::BadPort;
    } else if (service.GetPort() == default_port_main) {
        // Using mainnet port prohibited outside of mainnet
        return NetInfoStatus::BadPort;
    }

    return NetInfoStatus::Success;
}

NetInfoStatus MnNetInfo::AddEntry(const Purpose purpose, const std::string& input)
{
    // We only support storing Core P2P addresses, so the max limit for any other
    // purpose is 0 but even if it's a Core P2P address, we only support one entry,
    // so if we have anything stored already, we're full.
    if (purpose != Purpose::CORE_P2P || !IsEmpty()) {
        return NetInfoStatus::MaxLimit;
    }
    if (auto service = Lookup(input, /*portDefault=*/Params().GetDefaultPort(), /*fAllowLookup=*/false); service.has_value()) {
        const auto ret = ValidateService(service.value());
        if (ret == NetInfoStatus::Success) {
            if (service == addr.data) {
                // Not possible since we allow only one value at most
                return NetInfoStatus::Duplicate;
            }
            addr = NetInfoEntry(service.value());
        }
        return ret;
    }
    return NetInfoStatus::BadInput;
}

NetInfoList MnNetInfo::GetEntries() const
{
    NetInfoList ret;
    if (!IsEmpty() && addr.IsTriviallyValid()) {
        ret.push_back(addr);
    }
    // If NetInfoEntry is empty or invalid, we probably want to skip code that expects valid
    // entries to iterate through, so we return a blank set instead.
    return ret;
}

UniValue MnNetInfo::ToJson() const
{
    UniValue ret(UniValue::VOBJ);
    ret.pushKV(PurposeToString(Purpose::CORE_P2P, /*lower=*/true), ArrFromService(addr.data));
    return ret;
}

std::string MnNetInfo::ToString() const
{
    return strprintf("MnNetInfo()\n"
    // Extra padding to account for padding done by the calling function.
                     "    NetInfo(purpose=%s)\n"
                     "      %s\n",
                     PurposeToString(Purpose::CORE_P2P), addr.ToString());
}
