name: Build source

on:
  workflow_call:
    inputs:
      build-target:
        description: "Target name as defined by inputs.sh"
        required: true
        type: string
      container-path:
        description: "Path to built container at registry"
        required: true
        type: string
      depends-key:
        description: "Key needed to access cached depends"
        required: true
        type: string
    outputs:
      key:
        description: "Key needed for restoring build outputs"
        value: ${{ jobs.build-src.outputs.key }}

jobs:
  build-src:
    name: Build source
    runs-on: ubuntu-24.04
    outputs:
      key:  ${{ steps.bundle.outputs.key }}
    container:
      image: ${{ inputs.container-path }}
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Initial setup
        id: setup
        run: |
          git config --global --add advice.detachedHead false
          git config --global --add safe.directory "$PWD"
          GIT_HEAD="$(git rev-parse HEAD)"
          git checkout develop
          git checkout "${GIT_HEAD}"
          BUILD_TARGET="${{ inputs.build-target }}"
          source ./ci/dash/matrix.sh
          echo "HOST=${HOST}" >> $GITHUB_OUTPUT
          echo "PR_BASE_SHA=${{ github.event.pull_request.base.sha || '' }}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Restore SDKs cache
        uses: actions/cache/restore@v4
        if: inputs.build-target == 'mac'
        with:
          path: |
            depends/SDKs
          key: depends-sdks-${{ hashFiles('depends/hosts/darwin.mk') }}
          fail-on-cache-miss: true

      - name: Restore depends cache
        uses: actions/cache/restore@v4
        with:
          path: |
            depends/built
            depends/${{ steps.setup.outputs.HOST }}
          key: ${{ inputs.depends-key }}
          fail-on-cache-miss: true

      - name: Manage ccache
        uses: actions/cache@v4
        with:
          path: |
            /cache
          key: ccache-${{ hashFiles('contrib/containers/ci/Dockerfile', 'depends/packages/*') }}-${{ inputs.build-target }}-${{ github.sha }}
          restore-keys: |
            ccache-${{ hashFiles('contrib/containers/ci/Dockerfile', 'depends/packages/*') }}-${{ inputs.build-target }}-

      - name: Build source and run unit tests
        run: |
          CCACHE_SIZE="400M"
          CACHE_DIR="/cache"
          BUILD_TARGET="${{ inputs.build-target }}"
          source ./ci/dash/matrix.sh
          ./ci/dash/build_src.sh
          ./ci/dash/test_unittests.sh
        shell: bash

      - name: Bundle outputs and artifacts
        id: bundle
        run: |
          export BUILD_TARGET="${{ inputs.build-target }}"
          ./ci/dash/bundle-output.sh create
          ARTIFACT_PATH="/output" ./ci/dash/bundle-build.sh
          echo "key=build-$(head -c 512 /dev/urandom | sha256sum | head -c 64)" >> "${GITHUB_OUTPUT}"
          echo "short-sha=$(git rev-parse --short=8 HEAD)" >> "${GITHUB_OUTPUT}"

      - name: Save build outputs
        uses: actions/cache/save@v4
        with:
          path: |
            output-${{ inputs.build-target }}.tar.zst
          key: ${{ steps.bundle.outputs.key }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ inputs.build-target }}-${{ steps.bundle.outputs.short-sha }}
          path: |
            /output/artifacts-${{ inputs.build-target }}.tar.zst
            /output/artifacts-${{ inputs.build-target }}.tar.zst.sha256
          compression-level: 0
          overwrite: true
          retention-days: 1
