name: Test source

on:
  workflow_call:
    inputs:
      build-key:
        description: "Key needed to access cached build output"
        required: true
        type: string
      build-target:
        description: "Target name as defined by inputs.sh"
        required: true
        type: string
      container-path:
        description: "Path to built container at registry"
        required: true
        type: string

env:
  INTEGRATION_TESTS_ARGS: "--extended --exclude feature_pruning,feature_dbcrash"

jobs:
  test-src:
    name: Test source
    runs-on: ubuntu-24.04
    container:
      image: ${{ inputs.container-path }}
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Restore build outputs
        uses: actions/cache/restore@v4
        with:
          path: |
            output-${{ inputs.build-target }}.tar.zst
          key: ${{ inputs.build-key }}
          fail-on-cache-miss: true

      - name: Run functional tests
        run: |
          git config --global --add advice.detachedHead false
          git config --global --add safe.directory "$PWD"
          export BUILD_TARGET="${{ inputs.build-target }}"
          ./ci/dash/bundle-output.sh extract
          source ./ci/dash/matrix.sh
          ./ci/dash/test_integrationtests.sh ${INTEGRATION_TESTS_ARGS}
        shell: bash
